/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:57647f17-02e3-4730-8749-46df8db8f6bd",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_GxmGSnsCG",
    "aws_user_pools_web_client_id": "7cdet801ec8tms7lispog4cmmn",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://bejoyzjlhvgxpbhs6iim6fviqq.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-bjnn24dbrzbx3hcbxo7y6e3m2m"
};


export default awsmobile;
