/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:57647f17-02e3-4730-8749-46df8db8f6bd",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_GxmGSnsCG",
    "aws_user_pools_web_client_id": "7cdet801ec8tms7lispog4cmmn",
    "oauth": {}
};


export default awsmobile;
