const initStats = {
    character: {
        name: "Rey Whatsherface",
        player_name: "esila",
        species: "Human",
        credits: "100",
        total_xp: "100",
        available_xp: "100",
        career: "Sentinel",
        specializations: [{name: "Knight", in_career: "yes"}],
        gender: "",
        age: "",
        height: "",
        build: "",
        hair: "",
        eyes: "",
        notable_features: "",
        other: "",
        motivations_1_category: "",
        motivations_1_type: "",
        motivations_1_description: "",
        motivations_2_category: "",
        motivations_2_type: "",
        motivations_2_description: ""
    },
    characteristics: {Brawn: "3", Agility: "4", Intellect: "3", Cunning: "3", Willpower: "5", Presence: "3"},
    generalSkills: {
        Astrogation: {name: "Astrogation", characteristic: "Intellect", career: false, rank: 0, extraDice: ""},
        Athletics: {name: "Athletics", characteristic: "Brawn", career: false, rank: 0, extraDice: ""},
        Charm: {name: "Charm", characteristic: "Presence", career: false, rank: 0, extraDice: ""},
        Coercion: {name: "Coercion", characteristic: "Willpower", career: false, rank: 0, extraDice: ""},
        Computers: {name: "Computers", characteristic: "Intellect", career: false, rank: 0, extraDice: ""},
        Cool: {name: "Cool", characteristic: "Presence", career: false, rank: 0, extraDice: ""},
        Coordination: {name: "Coordination", characteristic: "Agility", career: false, rank: 0, extraDice: ""},
        Deception: {name: "Deception", characteristic: "Cunning", career: false, rank: 0, extraDice: ""},
        Discipline: {name: "Discipline", characteristic: "Willpower", career: true, rank: "2", extraDice: ""},
        Leadership: {name: "Leadership", characteristic: "Presence", career: true, rank: "2", extraDice: ""},
        Mechanics: {name: "Mechanics", characteristic: "Intellect", career: true, rank: "2", extraDice: ""},
        Medicine: {name: "Medicine", characteristic: "Intellect", career: false, rank: 0, extraDice: ""},
        Negotiation: {name: "Negotiation", characteristic: "Presence", career: false, rank: 0, extraDice: ""},
        Perception: {name: "Perception", characteristic: "Cunning", career: false, rank: 0, extraDice: ""},
        PilotingPlanetary: {
            name: "PilotingPlanetary",
            characteristic: "Agility",
            career: false,
            rank: 0,
            extraDice: ""
        },
        PilotingSpace: {name: "PilotingSpace", characteristic: "Agility", career: false, rank: 0, extraDice: ""},
        Resilience: {name: "Resilience", characteristic: "Brawn", career: false, rank: 0, extraDice: ""},
        Skulduggery: {name: "Skulduggery", characteristic: "Cunning", career: false, rank: 0, extraDice: ""},
        Stealth: {name: "Stealth", characteristic: "Agility", career: false, rank: 0, extraDice: ""},
        Streetwise: {name: "Streetwise", characteristic: "Cunning", career: false, rank: 0, extraDice: ""},
        Survival: {name: "Survival", characteristic: "Cunning", career: true, rank: "2", extraDice: ""},
        Vigilance: {name: "Vigilance", characteristic: "Willpower", career: false, rank: 0, extraDice: ""}
    },
    combatSkills: {
        Brawl: {name: "Brawl", characteristic: "Brawn", career: false, rank: 0, extraDice: ""},
        Gunnery: {name: "Gunnery", characteristic: "Agility", career: false, rank: 0, extraDice: ""},
        Lightsaber: {name: "Lightsaber", characteristic: "Brawn", career: true, rank: "2", extraDice: ""},
        Melee: {name: "Melee", characteristic: "Brawn", career: false, rank: 0, extraDice: ""},
        RangedLight: {name: "RangedLight", characteristic: "Agility", career: false, rank: 0, extraDice: ""},
        RangedHeavy: {name: "RangedHeavy", characteristic: "Agility", career: false, rank: 0, extraDice: ""}
    },
    knowledgeSkills: {
        CoreWorlds: {
            name: "CoreWorlds",
            characteristic: "Intellect",
            career: false,
            rank: 0,
            extraDice: ""
        },
        Education: {name: "Education", characteristic: "Intellect", career: false, rank: 0, extraDice: ""},
        Lore: {name: "Lore", characteristic: "Intellect", career: false, rank: 0, extraDice: ""},
        OuterRim: {name: "OuterRim", characteristic: "Intellect", career: true, rank: "1", extraDice: ""},
        Underworld: {name: "Underworld", characteristic: "Intellect", career: false, rank: 0, extraDice: ""},
        Xenology: {name: "Xenology", characteristic: "Intellect", career: false, rank: 0, extraDice: ""}
    },
    soakWounds: {
        soak: 1,
        wounds: {threshold: 1, current: 0},
        strain: {threshold: 1, current: 0},
        defense: {range: 0, melee: 0},
        encumberance: {threshold: 1, current: 0},
        force_rating: {threshold: 0, committed: 0}
    },
    weapons: [{
        make_model: "Lightsaber",
        weapon_type: "Lightsaber",
        modifiers: "",
        book_page: "",
        restricted: "No",
        features: "",
        range: "Engaged",
        skill: "Lightsaber",
        condition: "New",
        rarity: "",
        value: "",
        qualities: "Breach - Ignore up to 10 soak",
        damage: "8",
        critical: "1",
        encumberance: 0,
        hp: 0,
        attachments: [{attachment_name: "", hard_points: 0, base_modifiers: "", modifications: "", book_page: ""}]
    }, {
        make_model: "Blaster Pistol (Light)",
        weapon_type: "Blaster",
        modifiers: "",
        book_page: "",
        restricted: "No",
        features: "",
        range: "medium",
        skill: "RangedLight",
        condition: "New",
        rarity: "",
        value: "",
        qualities: "",
        damage: 0,
        critical: 0,
        encumberance: 0,
        hp: 0,
        attachments: [{attachment_name: "Scope", hard_points: "", base_modifiers: "", modifications: "", book_page: ""}]
    }]
};

export default initStats